config/routes.rb
Bonotres::Application.routes.draw do
  devise_for :users
  root :to => "home#index"
  resources :user_files

  match 'clients' => 'home#index_backoffice', :as => :clients
  match 'home_products' => 'home#products', :as => :home_products
  match 'home_products' => 'home#products', :as => :home_products
  match 'home_about_us' => 'home#about_us', :as => :home_about_us
  match 'home_careers' => 'home#careers', :as => :home_careers

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :user_file
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :database

  belongs_to :user
  mount_uploader :database, DatabaseUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render :layout => "static"
  end

  def about_us
    render :layout => "static"
  end

  def carrers
    render :layout => "static"
  end

  def products
    render :layout => "static"
  end

  def index_backoffice
    @user_file = UserFile.new
    @user_file.user = current_user
  end

end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController

  def index
    @user_files = UserFile.all
  end
  
  def create
    user_file = UserFile.new(params[:user_file])
    user_file.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_navigation.html.erb
<ul class="sf-menu">
  <li class="current"><%= link_to "Home", root_url %>
    <!--ul>
      <li><a href="#">Who We Are</a></li>
      <li><a href="#">Latest News</a></li>
      <li><a href="#">Contacts</a></li>
    </ul-->
  </li>
  <li><%= link_to "About us", home_about_us_url %></li>
  <li><%= link_to "Services", home_products_url %></li>
  <li><%= link_to "Carrers", home_careers_url %></li>
  <li><%= link_to "Login", clients_url %></li>
</ul>

app/views/home/about_us.html.erb
<!--==============================header=================================-->
<div class="bg">
	<div class="header">
      <div class="container_24">
        <div class="grid_24">
          <header>
              <div class="logo">
                  <h1><a href="index.html"><img src="assets/logo.png" alt=""></a></h1>
              </div>
              <nav>
                <%= render :partial => "navigation" %>
              </nav>
              <div class="clear"></div>
          </header>
        </div>
        <div class="clear"></div>
      </div>
    </div>
</div>
<!--==============================content================================-->
  <section id="content">
    <div class="container_24">
        <div class="box-row-2 wrapper">
            <div class="grid_6">
              <div class="box">
                  <a href="#" class="box-1"><strong>Strong</strong></a>
              </div>
            </div>
            <div class="grid_6">
              <div class="box">
                  <a href="#" class="box-2"><strong>Stable</strong></a>
              </div>
            </div>
            <div class="grid_6">
              <div class="box">
                  <a href="#" class="box-3"><strong>Standards</strong></a>
              </div>
            </div>
            <div class="grid_6">
              <div class="box">
                  <a href="#" class="box-4"><strong>e-Commerce</strong></a>
              </div>
            </div>
        </div>
        <div class="wrapper pad1">
          <div class="grid_14 wrap business">
              <img src="assets/page-2-img-1.jpg" alt="" class="img-indent">
              <div class="extra-wrap">
                  <h2 class="p5">Our Business</h2>
                  <!--p class="p6"><a href="#" class="color-1">Pellentesque sed dolor. Aliquam congue fermentum nisl Maurisaccumsan nulla vel diam, Sed in lacus.</a></p-->
                  <p>We are an e-Commerce Database Optimization Services company based in Los Angeles, CA serving top brands <strong>worldwide</strong>.</p>
              </div>
          </div>
          <!--div class="grid_9 prefix_1">
              <h2 class="p5">Testimonials</h2>
              <blockquote class="quotes p6">Adipis nullam consequat scelerisque urna, sed sollicitu
          proin dictum elementum velit. Fusce euismod consequat
          ante. Lorem ipsum dolor sit amet, consec...”
                  <a href="#" class="color-3">Bradley Grosh, manager</a>
              </blockquote>
                <blockquote class="quotes">Quisque nulla. Vestibulum libero nisl, porta vel, scelerisque cursus leo vel metus. Nulla facilisi. Aenean nec eros, ves
          tibulum ante ipsum primis in faucibus orci luctus et ultrices сurae; Suspendisse sollicitudin...”
                  <a href="#" class="color-3">Jessica Priston, production director</a>
              </blockquote>
          </div>
        </div-->
        <!--div class="grid_24 line pad2"></div>
        <div class="grid_24">
            <h2 class="p1">Our People</h2>
            <div class="wrap">
            	<div class="block-1">
                	<img src="assets/page-2-img-2.jpg" alt="">
                    <a href="#" class="color-3">Mark Johnson</a>
                    <p>Product Manager</p>
                </div>
                <div class="block-1">
                	<img src="assets/page-2-img-3.jpg" alt="">
                    <a href="#" class="color-3">Olivia Grosh</a>
                    <p>Support Manager</p>
                </div>
                <div class="block-1">
                	<img src="assets/page-2-img-4.jpg" alt="">
                    <a href="#" class="color-3">Patrick Pool</a>
                    <p>President</p>
                </div>
                <div class="block-1">
                	<img src="assets/page-2-img-5.jpg" alt="">
                    <a href="#" class="color-3">Stella Franklin</a>
                    <p>Project manager</p>
                </div>
                <div class="block-1">
                	<img src="assets/page-2-img-6.jpg" alt="">
                    <a href="#" class="color-3">Sam Kromstain</a>
                    <p>Software developer</p>
                </div>
                <div class="block-1 last">
                	<img src="assets/page-2-img-7.jpg" alt="">
                    <a href="#" class="color-3">John Anderson</a>
                    <p>CEO</p>
                </div>
            </div>
        </div-->
        <div class="clear"></div>
      </div>
  </section>
<!--==============================footer=================================-->
<footer>
	 <div class="container_24">
        <div class="grid_14">
        	<a href="index.html"><img src="assets/footer-logo.png" alt=""></a>
  			<p class="font-13"><span>Phone: +1 800 559 6580</span>  E-mail: <a href="#" class="color-2">contact@db-bud.com</a></p>
            <p class="font-11">&copy; 2013 : <a href="index-6.html" class="color-2">PRIVACY POLICY</a></p>
        </div>
        <!--div class="grid_6 prefix_4">
  			<p><span>Connect With Us</span><a href="#" class="tooltips"><img src="assets/icon-1.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-2.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-3.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-4.jpg" alt=""></a></p>
        </div-->
        <div class="clear"></div>
     </div>
</footer>

app/views/home/careers.html.erb
<!--==============================header=================================-->
<div class="bg">
	<div class="header">
      <div class="container_24">
        <div class="grid_24">
          <header>
              <div class="logo">
                  <h1><a href="index.html"><img src="assets/logo.png" alt=""></a></h1>
              </div>
              <nav>
                <%= render :partial => "navigation" %>
              </nav>
              <div class="clear"></div>
          </header>
        </div>
      </div>
    </div>
</div>
<!--==============================content================================-->
  <section id="content">
     <div class="container_24 spec_box">
        <div class="grid_6">
        	<h2 class="top-6 p7">24/7 Support</h2>
            <img src="assets/page-5-img-1.jpg" alt="">
            <p class="top-3">Contact us at <a href="#" class="color-2">contact@db-bud.com</a>. </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <div class="grid_6">
        	<h2 class="top-6 p7">Technical Support</h2>
            <img src="assets/page-5-img-2.jpg" alt="">
            <p class="top-3">Contact us at <a href="#" class="color-2">contact@db-bud.com</a>.</p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <div class="grid_6">
        	<h2 class="top-6 p7">Sale representative</h2>
            <img src="assets/page-5-img-3.jpg" alt="">
            <p class="top-3">Contact us at <a href="#" class="color-2">contact@db-bud.com</a>. </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <div class="grid_6">
        	<h2 class="top-6 p7">Software Engineer</h2>
            <img src="assets/page-5-img-4.jpg" alt="">
            <p class="top-3">Contact us at <a href="#" class="color-2">contact@db-bud.com</a>. </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <!--div class="grid_24 line pad-1"></div>
        <div class="grid_11">
        	<h2 class="p9">Support Resources:</h2>
            <div class="wrap block-4">
            	<div class="number">01</div>
                <div class="extra-wrap">
                	<p><a href="#" class="color-1">Acquired Companies Product Support</a></p>
                	<p class="top-4">Adipis nullam consequat scelerisque urna, sed sollicitudin elit lob
ortis varius. Suspendisse ac venenatis velit. Quisque nulla.</p>
                </div>
            </div>
            <div class="wrap block-4 top-9">
            	<div class="number">02</div>
                <div class="extra-wrap">
                	<p><a href="#" class="color-1">Critical Patch Updates and Security Alerts</a></p>
                	<p class="top-4">Duis tempor, nibh in varius auctor, metus felis malesuada
entesque quam vitae habitasse platea dictumst. Aenean sit amet.</p>
                </div>
            </div>
            <div class="wrap block-4 top-9">
            	<div class="number">03</div>
                <div class="extra-wrap">
                	<p><a href="#" class="color-1">Our Company Product Documentation</a></p>
                	<p class="top-4">Aenean sit amet libero ac velit porttitor iaculis. Nullam vitae porta massa. Nulla pretium lacus id ante malesuada.</p>
                </div>
            </div>
        </div>
        <div class="grid_12 prefix_1">
        	<h2 class="p5">Corporate Governance</h2>
            <div class="wrap business">
                <img src="assets/page-5-img-5.jpg" alt="" class="img-indent-3">
                <div class="extra-wrap ">
                    <p class="p6"><a href="#" class="color-1">quam congue fermentum nisl Mauri</a></p>
                    <p>Praesent vestibulum molestie lacus.
drerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesua.</p>
                </div>
            </div>
            <p class="top-10">Praesent vestibulum molestie lacus, drerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesua.da odio. Morbi nunc odio, gravida at.</p>
        </div-->
        <div class="clear"></div>
      </div>
  </section>
<!--==============================footer=================================-->
<footer>
	 <div class="container_24">
        <div class="grid_14">
        	<a href="index.html"><img src="assets/footer-logo.png" alt=""></a>
  			<p class="font-13"><span>Phone: +1 800 559 6580</span>  E-mail: <a href="#" class="color-2">contact@db-bud.com</a></p>
            <p class="font-11">&copy; 2013 : <a href="index-6.html" class="color-2">PRIVACY POLICY</a></p>
        </div>
        <!--div class="grid_6 prefix_4">
  			<p><span>Connect With Us</span><a href="#" class="tooltips"><img src="assets/icon-1.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-2.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-3.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-4.jpg" alt=""></a></p>
        </div-->
        <div class="clear"></div>
     </div>
</footer>

app/views/home/index.html.erb
<!--==============================header=================================-->
<div class="bg">
	<div class="header">
      <div class="container_24">
        <div class="grid_24">
          <header>
            <div class="logo">
                <h1><a href="index.html"><img src="<%= asset_path 'logo.png' %>  " alt=""></a></h1>
            </div>
            <nav>
              <%= render :partial => "navigation" %>
            </nav>
            <div class="clear"></div>
          </header>
        </div>
        <div class="clear"></div>
      </div>
    </div>
</div>
<!--==============================content================================-->
  <section id="content">
    <div class="container_24">
      <div class="wrapper">
        <div class="grid_24">
          <div class="flexslider">
            <ul class="slides">
               <li><img src="<%= asset_path 'slider-1.jpg' %>"
               alt=""><div class="banner"><p>Upload your emailing
               list to our <strong>secured</strong> tool</p></div></li>
               <li><img src="<%= asset_path 'slider-2.jpg' %>"
               alt=""><div class="banner"><p>Let us work maximizing
               <strong>your</strong> database</p></div></li>
               <li><img src="<%= asset_path 'slider-3.jpg' %>"
               alt=""><div class="banner"><p>Get a
               complete <strong>free</strong> report on your enhanced database</p></div></li>
               <li><img src="<%= asset_path 'slider-4.jpg' %>"
               alt=""><div class="banner"><p> Minimize
               un-subscriptions, <strong>empower</strong> your newsletters.</p></div></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="box-row wrapper">
          <div class="grid_6">
            <div class="box">
                <a href="#" class="box-1"><strong>Upload</strong></a>
            </div>
          </div>
          <div class="grid_6">
            <div class="box">
                <a href="#" class="box-2"><strong>Clean & Qualify</strong></a>
            </div>
          </div>
          <div class="grid_6">
            <div class="box">
                <a href="#" class="box-3"><strong>Get a report</strong></a>
            </div>
          </div>
          <div class="grid_6">
            <div class="box">
                <a href="#" class="box-4"><strong>Boost ROI</strong></a>
            </div>
          </div>
      </div>
     </div>
     <div class="container_24">
        <div class="grid_6">
            <h3 class="top-1 p2">Why Choose us?</h3>
            <p>DB bud offers powerfull services to boost you emailing database ROI by increasint you list deliverability and augmenting you targetting.</p>
<p> </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <div class="grid_6">
            <h3 class="top-1 p2">DB Cleaner</h3>
            <p>Cleans your DB, getting rid of hard bounces, robinsons, minimizing the risk of spam-traps.</p>
<p>What are you waiting to <strong>Boost Your Derivelability</strong>? </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <div class="grid_6">
            <h3 class="top-1 p2">DB Optimizer</h3>
            <p>Gets important data of your users, complementing your current information so you can target your newsletters to a whole new level.</p>
<p>Get more relevant and <strong>Boost your newsletter's ROI !</strong>. </p>
			<!--a href="#" class="button top-2">more</a-->
        </div>
        <!--div class="grid_6">
            <h3 class="top-1 p2">Featured Services</h3>
            <p>Natoqe penatus partur montes diculus duim fusegin alesda morb nuncodio.
Gravida curs necluctus tristique auctor ultricies acmsan malesuada.</p>
<p>Donec situmamet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. </p>
			<a href="#" class="button top-2">more</a>
        </div-->
        <div class="grid_24 line pad-1"></div>
        <div class="grid_11">
        	<h2 class="p3">Who We Are</h2>
            <img src="<%= asset_path 'page-1-img-1.jpg' %>" alt="">
            <p class="p1 top-3"><strong>e-Commerce Database Optimization Specialists</strong> based in Los Angeles, CA serving top brands <strong>worldwide</strong>.</p>
        </div>
        <!--div class="grid_12 prefix_1">
        	<h2 class="p4">Recent News</h2>
            <div class="wrap date">
            	<div class="date-text">27/02</div>
                <div class="extra-wrap">
                	<a href="#" class="color-1">Lorem ipsum dolor amet consectetur</a>
                    <p class="font-13 top-4">Adipis nullam consequat scelerisque urna, sed sollicitudin elit lobortis varius. Suspendisse ac venenatis velit.</p>
                </div>
            </div>
            <div class="wrap date top-5">
            	<div class="date-text">25/02</div>
                <div class="extra-wrap">
                	<a href="#" class="color-1">Lorem ipsum dolor amet consectetur</a>
                    <p class="font-13 top-4">Duis tempor, nibh in varius auctor, metus felis malesuada sed pellentesque quam vitae habitasse platea dictumst. Aenean sit amet libero ac velit porttitor iaculis.</p>
                </div>
            </div>
            <div class="wrap date top-5">
            	<div class="date-text">22/02</div>
                <div class="extra-wrap">
                	<a href="#" class="color-1">Lorem ipsum dolor amet consectetur</a>
                    <p class="font-13 top-4">Aenean sit amet libero ac velit porttitor iaculis. Nullam vitae porta massa. Nulla pretium lacus id ante malesuada.</p>
                </div>
            </div>
            <a href="#" class="button top-2">more</a>
        </div-->
        <!--div class="grid_24 banners">
        	<a href="#" class="banner-1"></a><a href="#" class="banner-2"></a><a href="#" class="banner-3"></a><a href="#" class="banner-4"></a><a href="#" class="banner-5 last"></a>
        </div>
        <div class="clear"></div-->
      </div>
  </section>
<!--==============================footer=================================-->
<footer>
	 <div class="container_24">
        <div class="grid_14">
        	<a href="index.html">
                  <img src="<%= asset_path 'footer-logo.png' %>" alt=""></a>
  			<p class="font-13"><span>Phone: +1 800 559 6580</span>  E-mail: <a href="#" class="color-2">contact@db-bud.com</a></p>
            <p class="font-11">&copy; 2013 : <a href="index-6.html" class="color-2">PRIVACY POLICY</a><!-- {%FOOTER_LINK} --></p>
        </div>
        <!--div class="grid_6 prefix_4">
  			<p><span>Connect With Us</span><a href="#"
  			class="tooltips">
                            <img src="<%= asset_path 'icon-1.jpg' %>" alt=""></a>
                          <a class="tooltips"><img src="<%= asset_path 'icon-2.jpg' %>" alt=""></a><a href="#"
  			class="tooltips">
                            <img src="<%= asset_path 'icon-3.jpg' %>" alt=""></a><a href="#"
  			class="tooltips">
                            <img src="<%= asset_path 'icon-4.jpg' %>" alt=""></a></p>
        </div-->
        <div class="clear"></div>
     </div>
</footer>

app/views/home/index_backoffice.html.erb
<% if user_signed_in? %>

<p>

  <p>
    <h2> Welcome back </h2>
  </p>
<p>

  <%= form_for @user_file, :html => { :multipart => true } do |f| %>
     <% if @user_file.errors.any? %>
       <% f.errors.full_messages.each do |error| %>
         <li><% error %></li>
       <% end %>
     <% end %>
     
     <p> <%= f.file_field :database %> </p>
     <p> <%= f.submit "Send" %> </p>
     
  <% end  %> 

<% else %>

  <%= link_to "Sign in", new_session_path(:user)  %><br />

<% end %>
</p>
</p>

app/views/home/products.html.erb
<!--==============================header=================================-->
<div class="bg">
	<div class="header">
      <div class="container_24">
        <div class="grid_24">
          <header>
              <div class="logo">
                  <h1><a href="index.html"><img src="assets/logo.png" alt=""></a></h1>
              </div>
              <nav>
                <%= render :partial => "navigation" %>
              </nav>
              <div class="clear"></div>
          </header>
        </div>
        <div class="clear"></div>
      </div>
    </div>
</div>
<!--==============================content================================-->
  <section id="content">
     <div class="container_24 gallery">
        <div class="grid_24">
        	<h2 class="top-6 p7">Our Services</h2>
            <div class="wrap">
                <div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-5.jpg" alt=""></a>
                    <p><strong>DB Cleaner</strong></p>
                    <p class="font-13 top-4">Cleans your DB, getting rid of hard bounces, robinsons, minimizing the risk of spam-traps.</p>
                </div>
                <div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-2.jpg" alt=""></a>
                    <p><strong>DB Optimizer</strong></p>
                    <p class="font-13 top-4">Gets important data of your users, complementing your current information so you can target your newsletters to a whole new level.</p>
                </div>
                <!--div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-3.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #3</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div>
                <div class="block-3 last">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-4.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #4</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div-->
            </div>
            <!--div class="wrap top-8">
                <div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-5.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #5</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div>
                <div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-6.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #6</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div>
                <div class="block-3">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-7.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #7</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div>
                <div class="block-3 last">
                	<a class="lightbox-image" href="#"><img src="assets/page-4-img-8.jpg" alt=""></a>
                    <p><a href="#" class="color-1">product #8</a></p>
                    <p class="font-13 top-4">Consectetuerlit sediam nonummibhn
cidunt utaoreet doloreagnarat volutpat
wisi enim toremen.</p>
                </div>
            </div-->
        </div>
        <div class="clear"></div>
      </div>
  </section>
<!--==============================footer=================================-->
<footer>
	 <div class="container_24">
        <div class="grid_14">
        	<a href="index.html"><img src="assets/footer-logo.png" alt=""></a>
  			<p class="font-13"><span>Phone: +1 800 559 6580</span>  E-mail: <a href="#" class="color-2">contact@db-bud.com</a></p>
            <p class="font-11">&copy; 2013 : <a href="index-6.html" class="color-2">PRIVACY POLICY</a></p>
        </div>
        <!--div class="grid_6 prefix_4">
  			<p><span>Connect With Us</span><a href="#" class="tooltips"><img src="assets/icon-1.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-2.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-3.jpg" alt=""></a><a href="#" class="tooltips"><img src="assets/icon-4.jpg" alt=""></a></p>
        </div-->
        <div class="clear"></div>
     </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bonotres" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "style", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Bonotres</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user %>
              <li><%= link_to "Sign out", destroy_session_path(:user),
              :method => :delete %></li>
              <% else %>
              <li><%= link_to "Sign in", new_session_path(:user) %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; Bonotres 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/user_files/create.html.erb
Thank you for uploading your file !

We will be in touch shortly